MyReview/Models/WriteReview.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyReview.Models
{
    public class WriteReview
    {
        public string CategoryId { get; set; }
        public string SubCategoryId { get; set; }
        public string UserId { get; set; }
        public string ProductRate { get; set; }
        public string AvgStarRate { get; set; }
        public string TotalLikes { get; set; }
        public string ReviewTitle { get; set; }
        public string ReviewDescription { get; set; }
        public string IsLikeProduct { get; set; }
        public string IsApproved { get; set; }
        public string FileName { get; set; }
        public string UserEmail { get; set; }        
    }
}

MyReview/Controllers/NewCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyReview.Models;

namespace MyReview.Controllers
{
    public class NewCategoryController : Controller
    {
        // GET: NewCategory
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(NewCategoryModel nCM)
        {
            if (!ModelState.IsValid)
            {
                
            }
            else
            {

            }
            return View();
        }
    }
}

MyReview/Controllers/ReviewController.cs
using MyReview.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MyReview.Controllers
{
    [Authorize]
    public class ReviewController : Controller
    {
        [AllowAnonymous]
        // GET: Review
        public ActionResult Index()
        {
            //List<ReviewsModel> listRecentReviewItems = GetRecentReviews();
            //if(listRecentReviewItems!=null && listRecentReviewItems.Count > 0)
            //{
            //    return View(listRecentReviewItems.ToList());
            //}
            //return View();

            ReviewCollectionModel rcModel = new ReviewCollectionModel();
            rcModel.TopRecentReviews = GetRecentReviews();
            rcModel.TrendingReviews = GetTrendingReviews();
            if (rcModel != null)
            {
                return View(rcModel);
            }
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Index(string keyword)
        {
            //Note : you can bind same list from database  
            List<SubCategoryModel> ObjList = GetSearchItems(keyword);
                //new List<SubCategoryModel>()
                //    {

            //        new SubCategoryModel {SubCategoryName="Latur",Description="Latur City is good" },
            //        new SubCategoryModel {SubCategoryName="Mumbai",Description="Mumbai city is huge" },
            //        new SubCategoryModel {SubCategoryName="Pune" ,Description="Pune city is cool" },
            //        new SubCategoryModel {SubCategoryName="Delhi",Description="Delhi city is crowdy" },
            //        new SubCategoryModel {SubCategoryName="Dehradun",Description="Dehradun city is pleasant" },
            //        new SubCategoryModel {SubCategoryName="Noida",Description="Noida city is creepy" },
            //        new SubCategoryModel {SubCategoryName="New Delhi",Description="New Delhi city is capital" }

            //};
            //Searching records from list using LINQ query  
            //var CityList = (from N in ObjList
            //                where N.SubCategoryName.StartsWith(Prefix)
            //                select new { N.SubCategoryName });
            return Json(ObjList, JsonRequestBehavior.AllowGet);
        }
       
        public ActionResult WriteReview()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddReview(FormCollection f, HttpPostedFileBase file)
        {
            HttpStatusCode hp = InsertReviewDetails(f["hdCategoryId"].ToString(), f["hdSubCategoryId"].ToString(), Convert.ToDecimal(f["hdStarRating"]), f["reviewtitle"].ToString(), f["comment"].ToString()
                , Convert.ToBoolean(f["optradio"]), file);

            if (hp.ToString() == "Created")
            {
                return Redirect("index");
            }
            //else error page
                return View("WriteReview");
        }
        [AllowAnonymous]
        public ActionResult AllReview()
        {
            List<ReviewsModel> rcModel = new List<ReviewsModel>();
            rcModel = GetAllReviews();
            if (rcModel != null)
            {
                return View(rcModel);
            }

            return View();
        }
        
        public ActionResult ReadMore(int reviewId)
        {
            ReviewsModel listRecentReviewItem = GetReviewById(reviewId);
            if (listRecentReviewItem != null)
            {
                return View(listRecentReviewItem);
            }
            return View();
        }
        [HttpPost]
        public ActionResult ReadMore(FormCollection f)
        {
            HttpStatusCode hp = InsertReviewVoting(Convert.ToInt16(f["hdReviewId"]), Convert.ToBoolean(f["optradio"]), Convert.ToDecimal(f["hdStarRating"]));

            if (hp.ToString() == "Created")
            {
                //success page
            }
            //else error page
            return View("ReadMore");
        }
        private List<SubCategoryModel> GetSearchItems(string keyword)
        {
            List<SubCategoryModel> items = new List<SubCategoryModel>();
            string constr = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = "SearchProducts";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    SqlParameter prodname = new SqlParameter("@prodname", keyword);
                    cmd.Parameters.Add(prodname);

                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            items.Add(new SubCategoryModel
                            {
                                SubCategoryId = sdr["SubCategoryId"].ToString(),
                                SubCategoryName = sdr["SubCategoryName"].ToString(),
                                Description = sdr["Description"].ToString(),
                                ImageName = sdr["ImageName"].ToString(),
                                CategoryId = sdr["CategoryId"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }

            return items;
        }

        public HttpStatusCode InsertReviewDetails(string catID, string subcatID, decimal productRate, string reviewtitle, string reviewDes, bool isLikeProduct, HttpPostedFileBase file)
        {
            if (Session["LoggedInUser"] != null)
            {
                UserModel um = (UserModel)Session["LoggedInUser"];
                string connStr = ConfigurationManager.ConnectionStrings["ConnectionString"].ToString();
                string sql = "dbo.InsertReviewDetails";
                using (SqlConnection conn = new SqlConnection(connStr))
                {
                    using (SqlCommand cmd = new SqlCommand(sql))
                    {
                        cmd.Connection = conn;
                        try
                        {
                            string fileName = string.Empty;
                            cmd.Parameters.Add("@pCatID", System.Data.SqlDbType.NVarChar).Value = catID;
                            cmd.Parameters.Add("@pSubCatID", System.Data.SqlDbType.NVarChar).Value = subcatID;
                            cmd.Parameters.Add("@pUserID", System.Data.SqlDbType.NVarChar).Value = um.UserId;
                            cmd.Parameters.Add("@pProductRate", System.Data.SqlDbType.Decimal).Value = productRate;
                            cmd.Parameters.Add("@pReviewTitle", System.Data.SqlDbType.NVarChar).Value = reviewtitle;
                            cmd.Parameters.Add("@pReviewDes", System.Data.SqlDbType.NVarChar).Value = reviewDes;
                            cmd.Parameters.Add("@pIsLikeProduct", System.Data.SqlDbType.Bit).Value = isLikeProduct;
                            if (file != null && file.ContentLength > 0)
                            {
                                Guid strGuid = Guid.NewGuid();
                                fileName = strGuid.ToString();
                                string imgPath = Path.Combine(Server.MapPath("~/ReviewUploads/" + fileName + Path.GetExtension(file.FileName)));
                                file.SaveAs(imgPath);
                                cmd.Parameters.Add("@pFileName", System.Data.SqlDbType.NVarChar).Value = fileName + Path.GetExtension(file.FileName);
                            }
                            else
                            {
                                cmd.Parameters.Add("@pFileName", System.Data.SqlDbType.NVarChar).Value = DBNull.Value;
                            }
                            
                            cmd.CommandType = System.Data.CommandType.StoredProcedure;
                            conn.Open();
                            cmd.ExecuteNonQuery();
                        }
                        catch (Exception ex)
                        {
                            return HttpStatusCode.BadRequest;
                        }
                    }
                }
            }
            else
            {
                return HttpStatusCode.Unauthorized;
            }
            return HttpStatusCode.Created;
        }
        [AllowAnonymous]
        public List<ReviewsModel> GetRecentReviews()
        {
            List<ReviewsModel> listRecentReview = null;
            string connStr = ConfigurationManager.ConnectionStrings["ConnectionString"].ToString();
            using (SqlConnection con = new SqlConnection(connStr))
            {
                string query = "GetTop4ProductReviews";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    try
                    {
                        cmd.Connection = con;
                        cmd.CommandType = System.Data.CommandType.StoredProcedure;
                        con.Open();
                        using (SqlDataReader sdr = cmd.ExecuteReader())
                        {
                            listRecentReview = new List<ReviewsModel>();
                            while (sdr.Read())
                            {
                                listRecentReview.Add(new ReviewsModel
                                {
                                    ReviewId = Convert.ToInt16(sdr["ReviewId"]),
                                    SubCategoryName = sdr["SubCategoryName"].ToString(),

MyReview/Views/Review/WriteReview.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>My Review!</title>

    <link href="~/Content/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="~/Scripts/valid.js"></script>
    <style>
        .checked {
            color: orange;
        }
    </style>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    @*star ratings-start*@
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="~/Content/star-rating.css" media="all" rel="stylesheet" type="text/css"  />
    @*star ratings-end*@
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    @*star ratings-start*@
    <script src="~/Scripts/star-rating.js"></script>
    @*star ratings-end*@
    <script type="text/javascript">
        $(document).ready(function () {
            $('#search').autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/Review/Index",
                        type: "POST",
                        dataType: "json",
                        data: { keyword: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { label: item };
                            }));
                        }
                    });
                },
                select: function (event, ui) {
                    //alert("SubCategoryId, CategoryId,ImageName: " + ui.item.label.SubCategoryId + ", " + ui.item.label.CategoryId + ", " + ui.item.label.ImageName);
                    var imgSrc = "../Content/img/" + ui.item.label.ImageName;
                    $("#imgProduct").attr('src', imgSrc);
                    $("#hdCategoryId").val(ui.item.label.CategoryId);
                    $("#hdSubCategoryId").val(ui.item.label.SubCategoryId);
                    $("#lblProductName").html(ui.item.label.SubCategoryName);
                    //$("#item_description").val(ui.item.description);
                    $('#search').val(ui.item.label.SubCategoryName + " - " + ui.item.label.Description);
                    return false;
                }
            }).data("ui-autocomplete")._renderItemData = function (ul, item) {
                return $("<li></li>")
                    .data("ui-autocomplete-item", item)
                    .append("<a>" + item.label.SubCategoryName + " - " + item.label.Description + "</a>")
                    .appendTo(ul);
                };

            $('#input-21e').on(
                'change', function () {
                    $("#hdStarRating").val($(this).val());
                }); 
        });
    </script>
</head>
<body>
    <nav class="navbar navbar-light navbar-expand-xs" style="background-color: #e3f2fd;">
        <!-- Navbar content -->
        <a class="navbar-brand" href="#">
            <img src="~/Content/img/logo.png" height="30px" />
            <!-- <span class="text-primary">My Review</span> -->
        </a>
        <!-- <button class="navbar-toggler .d-lg-none .d-xl-block" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button> -->
        <div class="" id="navbarSupportedContent">
            <nav class="nav">
                @*<a class="nav-link active " href="#">Login</a>
        <a class="nav-link m-0 p-1" href="#"><button type="button" class="btn btn-sm btn-outline-danger">Sign Up</button></a>
        <a class="nav-link m-0 p-1" href="#"><button type="button" class="btn btn-sm btn-outline-success" onclick="location.href='@Url.Action("Index","Review" )'">My Review</button></a>
        <a class="nav-link m-0 p-1" href="#"><button type="button" class="btn btn-sm btn-outline-success" onclick="location.href='@Url.Action("AllReview","Review" )'">All Review</button></a>*@
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()

                        <a class="nav-link m-0 p-1" href="#"><button type="button" class="btn btn-sm btn-outline-success" onclick="location.href='@Url.Action("Index","Review" )'">My Review</button></a>
                        <a class="nav-link m-0 p-1" href="#"><button type="button" class="btn btn-sm btn-outline-success" onclick="location.href='@Url.Action("AllReview","Review" )'">All Review</button></a>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                @Html.ActionLink("Hello " + User.Identity.Name + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                            </li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    }
                }
                else
                {
                    @*<ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                        <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                    </ul>*@
                }
            </nav>
        </div>
    </nav>
    <div class="container cont-new">
        <h4>Write a Review on Products and Services</h4>
        <div class="row">
            <div class="col-md-12 srch-panel">

                <div class="search-container">
                    <form action="/action_page.php">
                        <input type="text" placeholder="Search for products, brands, services, movies, places, etc." name="search" id="search" class="serchnew-input">
                        @*<button> <i class="fa fa-search"></i> </button>*@
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container cont-new">
        <h4>Write a Review on <span id="lblProductName"></span></h4>
        <div class="row">
            <div class="col-md-8 srch-panel">
                @using (Html.BeginForm("AddReview", "Review", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @*<div class="form-group">
                <div class="col-md-10">
                    <input type="file" name="file" />
                </div>
            </div>*@
                    @*<input type="submit" value="Registration" class="btn btn-default" />*@

                    @*<form method="post" action="~/Review/AddReview" enctype="multipart/form-data">*@
                    <input type="hidden" name="hdCategoryId" id="hdCategoryId" />
                    <input type="hidden" name="hdSubCategoryId" id="hdSubCategoryId" />
                    <input type="hidden" name="hdStarRating" id="hdStarRating" />
                    <div class="radio">
                        <label><span class="red">*</span> <span class="serch-input">Do you like this product?</span>  </label>  &nbsp;&nbsp;&nbsp;&nbsp;
                        <label><input type="radio" name="optradio" value="True" checked>Yes</label>
                        <label><input type="radio" name="optradio" value="False">No</label>
                    </div>
                    <div class="radio">
                        <label><span class="red">*</span><span class="serch-input"> Star Rating </span>  </label>
                        <input id="input-21e" value="0" type="text" class="rating" data-min=0 data-max=5 data-step=0.5 data-size="xs"
                               title="">

                        @*&nbsp;&nbsp;&nbsp;&nbsp;
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>*@
                    </div>
                    <div class="radio">
                        <input type="text" name="reviewtitle" class="fild serch-input " placeholder="Your review title will attract readers, so be creative.">
                    </div>
                    <div class="mt-top">
                        <textarea rows="4" cols="100" name="comment" class="serch-input" placeholder="Write your review about the product."></textarea>
                        @*<input type="file" name="filename" accept="image/*" placeholder="Upload Photo">*@
                        <input type="file" name="file" />
                    </div>
                    <div class="mt-top">
                        @*<button type="submit" class="btn btn-success" value="Submit Review" onclick="location.href='@Url.Action("Index","NewCategory" )'" />>Submit Review</button>*@
                        @*<input type="button"
                class="btn btn-success"
                value="Submit Review"
                onclick="location.href='@Url.Action("AddReview","Review" )'" />*@
                        <input type="submit" class="btn btn-success" value="Submit Review" />
                    </div>
                    @*</form>*@
                }
            </div>
            <div class="col-md-4 srch-panel">
                <img name="imgProduct" id="imgProduct" width="300">
            </div>
        </div>
    </div>
    <footer class="" style="background-color: #e3f2fd;">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link active p-1 m-0" href="#">Home |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-1 m-0" href="#">About Us |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-1 m-0" href="#">Contact Us |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-1 m-0" href="#">Terms & Conditions |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-1 m-0" href="#">Blog |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-1 m-0" href="#">Help</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link active" href="#"><img src="~/Content/img/facebook.png" width="40px" height="40px" /></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><img src="~/Content/img/linkedin.png" width="40px" height="40px" /></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><img src="~/Content/img/google.png" width="40px" height="40px" /></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><img src="~/Content/img/twitter.png" width="40px" height="40px" /></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <p class="text-center text-dark p-2 m-2">copyright&copy;2019 - All Rights Reserved</p>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
</body>
</html>